version: 2.1

jobs:
  restore:
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  lint:
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Lint JavaScript Files
          command: npm run lint
  wdio:
    docker:
      - image: circleci/node:stretch-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: cp environments/local-headless-chrome.env .env
      - run: mkdir output
      - run:
          name: Start Sample Express App in the background and run WebdriverIO tests
          command: (npm start > output/express.log &) && npm test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: output

workflows:
  version: 2.1
  restore_lint_wdio:
    jobs:
      - restore
      - lint:
          requires:
            - restore
      - wdio:
          requires:
            - restore